vim.g.vscode_style = "dark"
require('plugins')
require('keybindings')
require('options')
require('nvim-tree-config')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('whichkey-config')
require('cmp-config')
vim.cmd('colorscheme vscode')
